---
- block:
  - name: install required tools mentioned in percona docs
    ansible.builtin.apt:
      pkg:
        - curl
        - gnupg2
        - lsb-release
  - name: install percona package deb
    ansible.builtin.apt:
      deb: "https://repo.percona.com/apt/percona-release_latest.generic_all.deb"
  - name: update apt cache
    ansible.builtin.apt: "update_cache=yes"
  - name: setup percona repo and release
    ansible.builtin.command: "{{ item }}"
    loop:
      - "percona-release setup -y ps80"
      - "percona-release enable ps-80 release"
  - name: update apt cache
    ansible.builtin.apt: "update_cache=yes"
  - name: install percona server
    ansible.builtin.apt: "pkg=percona-server-server"
  tags:
    - percona
